### ISSUE TITLE
Characteristics and About won't show up

### ISSUE THREAD

**Issue by JudicialHunter** [Ellypse/Total-RP-3-Extended#130]
Even when I'm RPing with friends who I know have these filled, they are still blank. I have updated to the most recent version of TRP3E.

**Comment by Solanya** [comment]
This probably isn't an Extended related issue. Try updating Total RP 3 with the latest beta build : https://wow.curseforge.com/projects/total-rp-3/files/2572694

If this still doesn't work, enable Lua errors by typing `/console scriptErrors 1` then `/reload` and if an error pops up, please send us a screenshot or copy the full content.
