### ISSUE TITLE
Lua error for text generation

### ISSUE THREAD

**Issue by lindiwe-b** [Ellypse/Total-RP-3-Extended#153]
I was following along with Nikradicals YouTube tutorial, and I keep running into Lua errors whenever I make quests that target NPCs (both with her tutorial and on my own quests). I have no other addons running except TRP3 and the extended. I am new to this, which is why I tried mirroring the tutorial, so I could ensure it wasn't user error. It still might be, and if it is I apologise. 

Message: ...\AddOns\totalRP3_Extended\script\script_operands.lua:216: attempt to index local 'args' (a nil value)
Time: Sat Nov 17 14:05:31 2018
Count: 4
Stack: ...\AddOns\totalRP3_Extended\script\script_operands.lua:216: attempt to index local 'args' (a nil value)
...\AddOns\totalRP3_Extended\script\script_operands.lua:216: in function `codeReplacement'
...ddOns\totalRP3_Extended\script\script_generation.lua:198: in function <...ddOns\totalRP3_Extended\script\script_generation.lua:178>
...ddOns\totalRP3_Extended\script\script_generation.lua:229: in function <...ddOns\totalRP3_Extended\script\script_generation.lua:212>
...ddOns\totalRP3_Extended\script\script_generation.lua:275: in function <...ddOns\totalRP3_Extended\script\script_generation.lua:243>
...ddOns\totalRP3_Extended\script\script_generation.lua:660: in function `generateAndRunCondition'
Interface\AddOns\totalRP3_Extended\quest\quest.lua:681: in function <Interface\AddOns\totalRP3_Extended\quest\quest.lua:638>
Interface\AddOns\totalRP3_Extended\quest\quest.lua:767: in function `onClick'
...AddOns\totalRP3\modules\targetframe\target_frame.lua:76: in function <...AddOns\totalRP3\modules\targetframe\target_frame.lua:74>

Locals: args = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'args' (a nil value)"

Message: ...\AddOns\totalRP3_Extended\script\script_operands.lua:216: attempt to index local 'args' (a nil value)
Time: Sat Nov 17 14:04:21 2018
Count: 1
Stack: ...\AddOns\totalRP3_Extended\script\script_operands.lua:216: attempt to index local 'args' (a nil value)
...\AddOns\totalRP3_Extended\script\script_operands.lua:216: in function `codeReplacement'
...lRP3_Extended_Tools\script/conditions/conditions.lua:223: in function <...lRP3_Extended_Tools\script/conditions/conditions.lua:219>

Locals: args = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'args' (a nil value)"

Message: ...\AddOns\totalRP3_Extended\script\script_operands.lua:216: attempt to index local 'args' (a nil value)
Time: Sat Nov 17 14:04:21 2018
Count: 1
Stack: ...\AddOns\totalRP3_Extended\script\script_operands.lua:216: attempt to index local 'args' (a nil value)
...\AddOns\totalRP3_Extended\script\script_operands.lua:216: in function `codeReplacement'
...lRP3_Extended_Tools\script/conditions/conditions.lua:223: in function <...lRP3_Extended_Tools\script/conditions/conditions.lua:219>

Locals: args = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'args' (a nil value)"

**Comment by Solanya** [comment]
Hi. Are you using version 1.2.0, or 1.3.0 beta ?
Also can you right-click on your creation, select quick export and copy-paste the content of the textbox here ? This way I can check if I can reproduce the issue on my end or identify what might be happening.

**Comment by lindiwe-b** [comment]
Hi thanks for the quick response. I am using 1.2.0,

Here is my original campaign: 
^1^T^N1^N1013^N2^S1116184235Bfc26^N3^T^SIN^T^t^STY^SCA^SSC^T^t^Sdetails^T^t^SQE^T^Squest_1_first^T^SAC^T^N1^T^STY^STALK^SSC^Stalk_vendor^SCO^T^N1^T^N1^T^Si^Sunit_npc_id^t^N2^S==^N3^T^Sv^S16691^t^t^N2^S*^N3^T^N1^T^Si^Sunit_npc_id^t^N2^S==^N3^T^Sv^S16613^t^t^N4^S*^N5^T^N1^T^Si^Sunit_npc_id^t^N2^S==^N3^T^Sv^S16637^t^t^N6^S*^N7^T^N1^T^Si^Sunit_npc_id^t^N2^S==^N3^T^Sv^S16650^t^t^t^t^t^SBA^T^SIC^SINV_Misc_Book_04^SDE^SStores~`have~`it~`pretty~`easy,~`they~`renew~`their~`licences~`yearly.~`Travelling~`or~`temporary~`vendors~`need~`to~`submit~`more~`often.^SPR^B^SNA^SAsk~`a~`local~`vendor~`where~`you~`can~`apply.^SIN^B^t^SSC^T^Stalk_vendor^T^SST^T^S1^T^St^Sbranch^Sb^T^N1^T^Scond^T^N1^T^N1^T^Si^Sunit_npc_id^Sa^T^N1^Starget^t^t^N2^S==^N3^T^Sv^S16613^t^t^N2^S*^N3^T^N1^T^Si^Sunit_npc_id^Sa^T^N1^Starget^t^t^N2^S==^N3^T^Sv^S16691^t^t^N4^S*^N5^T^N1^T^Si^Sunit_npc_id^Sa^T^N1^Starget^t^t^N2^S==^N3^T^Sv^S16637^t^t^N6^S*^N7^T^N1^T^Si^Sunit_npc_id^Sa^T^N1^Starget^t^t^N2^S==^N3^T^Sv^S16650^t^t^t^SfailMessage^SYou~`must~`find~`a~`booth~`vendor.^Sn^S2^t^t^t^S3^T^Se^T^N1^T^Sid^Squest_markObjDone^Sargs^T^N1^S1116184235Bfc26~`quest_1_first^N2^Stalk_vendor^t^t^t^St^Slist^Sn^S4^t^S2^T^Se^T^N1^T^Sid^Sdialog_start^Sargs^T^N1^S1116184235Bfc26~`quest_1_first~`smc_cutscenes^t^t^t^St^Slist^Sn^S3^t^S5^T^Si^N1^Ss^N0^St^Sdelay^Sd^N5^Sc^N1^Sn^S6^t^S4^T^Se^T^N1^T^Sid^Squest_goToStep^Sargs^T^N1^S1116184235Bfc26~`quest_1_first~`step_2_end^t^t^t^St^Slist^Sn^S5^t^S6^T^Se^T^N1^T^Sid^Squest_start^Sargs^T^N1^S^t^t^t^St^Slist^t^t^t^t^SLI^T^t^SMD^T^SMO^SNO^t^SHA^T^t^STY^SQU^SIN^T^Ssmc_cutscenes^T^SMD^T^SCD^S16/11/18~`19:15:35^SCB^SMumsie-WyrmrestAccord^SSB^SMumsie-WyrmrestAccord^SMO^SNO^SSD^S16/11/18~`19:15:35^SV^N1^t^SBA^T^SDI^N0^t^SSC^T^t^SHA^T^t^SLI^T^t^SDS^T^N1^T^SRU^Starget^SLO^b^SEP^b^STX^SThis~`vendor~`seems~`to~`have~`a~`quiet~`booth,~`you~`walk~`up~`and~`they~`greet~`you.~`"Hi~`there,~`how~`can~`I~`help~`you~`today?"^SBG^SInterface\DRESSUPFRAME\DressUpBackground-Bloodelf1^SLU^Splayer^SCH^T^N1^T^STX^S"I~`am~`in~`need~`of~`a~`temporary~`vendor~`permit,~`can~`you~`help~`me?"^SC^T^N1^T^N1^T^Si^Sunit_npc_id^Sa^T^N1^Starget^t^t^N2^S==^N3^T^Sv^S16650^t^t^N2^S*^N3^T^N1^T^Si^Sunit_npc_id^Sa^T^N1^Starget^t^t^N2^S==^N3^T^Sv^S16691^t^t^N4^S*^N5^T^N1^T^Si^Sunit_npc_id^Sa^T^N1^Starget^t^t^N2^S==^N3^T^Sv^S16613^t^t^N6^S*^N7^T^N1^T^Si^Sunit_npc_id^Sa^T^N1^Starget^t^t^N2^S==^N3^T^Sv^S16637^t^t^t^SN^N2^t^t^t^N2^T^STX^S"You~`will~`need~`to~`go~`to~`Sunfury~`Spire.~`If~`you~`ask~`around~`they~`will~`direct~`you~`to~`who~`to~`talk~`to."^SLO^b^SEP^B^SLU^Splayer^SBG^SInterface\DRESSUPFRAME\DressUpBackground-Bloodelf1^SRU^Starget^t^t^STY^SDI^t^t^SST^T^Sstep_1_first^T^SMD^T^SMO^SNO^t^SBA^T^STX^SFind~`an~`SMC~`booth~`vendor~`that~`is~`willing~`to~`share~`information~`with~`you.^SNA^Sstep_1_first^SIN^B^SFI^b^t^SSC^T^t^SHA^T^t^STY^SST^SLI^T^t^SIN^T^t^SAC^T^t^t^Sstep_2_end^T^SMD^T^SMO^SNO^t^SBA^T^STX^SQuest~`complete.^SNA^Sstep_2_end^SIN^b^SFI^B^t^SSC^T^t^SHA^T^t^STY^SST^SLI^T^t^SIN^T^t^SAC^T^t^t^t^SOB^T^Stalk_vendor^T^STX^STalk~`to~`an~`SMC~`Booth~`Vendor^SAA^B^t^t^t^t^SMD^T^SCD^S16/11/18~`18:42:35^SSB^SMumsie-WyrmrestAccord^SV^N47^SCB^SMumsie-WyrmrestAccord^SMO^SNO^SdV^S1.2.0^StV^N1013^SSD^S17/11/18~`12:52:58^SLO^Sen^t^SND^T^t^SHA^T^t^SsecurityLevel^N3^SBA^T^SIC^SINV_Misc_PaperBundle02a^SRA^S1~`-~`100^SDE^SWhenever~`visiting~`a~`major~`city~`buskers~`and~`vendors~`must~`submit~`a~`permit~`to~`the~`local~`guilds~`so~`they~`don't~`get~`thrown~`in~`the~`clink.~`Find~`the~`out~`where~`you~`need~`to~`apply~`for~`your~`permit.^SIM^SGarrZoneAbility-Stables^SNA^SObtain~`a~`SMC~`Vendor~`Permit.^t^SLI^T^t^SAC^T^t^t^N4^S1.2.0^t^^

Here is the follow along I was doing with the tutorial video:
^1^T^N1^N1013^N2^S1117132053Mduyc^N3^T^SIN^T^t^STY^SCA^SSC^T^t^Sdetails^T^t^SQE^T^Squest_1_first^T^SAC^T^N1^T^STY^STALK^SSC^Son_talk_toddrick^SCO^T^N1^T^N1^T^Si^Sunit_name^Sa^T^N1^Starget^t^t^N2^S==^N3^T^Sv^SToddrick^t^t^t^t^t^SBA^T^SIC^SINV_Misc_1H_InnMeatCleaver_A_01^SDE^SSeek~`out~`a~`butcher~`and~`ask~`how~`to~`find~`the~`cow~`level.^SPR^B^SNA^SHow~`do~`you~`find~`it?^SIN^B^t^SSC^T^Son_talk_toddrick^T^SST^T^S1^T^Sb^T^N1^T^Scond^T^N1^T^N1^T^Si^Sunit_name^Sa^T^N1^Starget^t^t^N2^S==^N3^T^Sv^SToddrick^t^t^t^Sn^S2^t^t^St^Sbranch^t^S3^T^Se^T^N1^T^Sid^Squest_markObjDone^Sargs^T^N1^S1117132053Mduyc~`quest_1_first^N2^Stoddrick^t^t^t^St^Slist^Sn^S4^t^S2^T^Se^T^N1^T^Sid^Sdialog_start^Sargs^T^N1^S1117132053Mduyc~`quest_1_first~`toddrick_cutscene^t^t^t^St^Slist^Sn^S3^t^S5^T^Si^N1^Ss^N0^St^Sdelay^Sd^N5^Sc^N1^Sn^S6^t^S4^T^Se^T^N1^T^Sid^Squest_goToStep^Sargs^T^N1^S1117132053Mduyc~`quest_1_first~`step_1_first^t^t^t^St^Slist^Sn^S5^t^S7^T^Se^T^N1^T^Sid^Squest_start^Sargs^T^N1^S1117132053Mduyc~`to_find_or_not_to_find_^t^t^t^St^Slist^t^S6^T^Se^T^N1^T^Sid^Squest_goToStep^Sargs^T^N1^S1117132053Mduyc~`quest_1_first~`step_2_^t^t^t^St^Slist^Sn^S7^t^t^t^t^SLI^T^t^SMD^T^SMO^SNO^t^SHA^T^t^STY^SQU^SIN^T^Stoddrick_cutscene^T^SMD^T^SCD^S17/11/18~`13:35:51^SCB^SKazandra-WyrmrestAccord^SSB^SKazandra-WyrmrestAccord^SMO^SNO^SSD^S17/11/18~`13:35:51^SV^N1^t^SBA^T^SDI^N0^t^SSC^T^t^SHA^T^t^SLI^T^t^SDS^T^N1^T^STX^SWhat~`can~`I~`get~`for~`you?^SLO^b^SEP^b^SRU^Starget^SLU^Splayer^SCH^T^N1^T^STX^SHow~`do~`I~`get~`to~`the~`cow~`level?^SN^N2^t^t^t^N2^T^SRU^Starget^SLO^b^SEP^B^SLU^Splayer^STX^SYou~`must~`kill~`a~`cow~`to~`get~`to~`the~`cow~`level.^t^t^STY^SDI^t^t^SST^T^Sstep_1_first^T^SMD^T^SMO^SNO^t^SBA^T^STX^STalking~`with~`Toddrick.^SNA^Sstep_1_first^SIN^B^SFI^b^t^SSC^T^t^SHA^T^t^STY^SST^SLI^T^t^SIN^T^t^SAC^T^t^t^Sstep_2_^T^SMD^T^SMO^SNO^t^SBA^T^SIN^b^SNA^Sstep_2_^STX^SWe~`know~`how,~`let's~`find~`a~`cow.^SFI^B^t^SSC^T^t^SHA^T^t^STY^SST^SLI^T^t^SIN^T^t^SAC^T^t^t^t^SOB^T^Stoddrick^T^STX^SSpeak~`with~`Toddrick~`in~`Goldshire.^SAA^B^t^t^t^Sto_find_or_not_to_find_^T^SAC^T^N1^T^STY^SACTION^SSC^Son_dead_cow^SCO^T^N1^T^N1^T^Si^Sunit_name^Sa^T^N1^Starget^t^t^N2^S==^N3^T^Sv^SCow^t^t^N2^S+^N3^T^N1^T^Si^Sunit_is_dead^t^N2^S==^N3^T^Si^Sunit_is_dead^Sa^T^N1^Starget^t^t^t^t^t^t^STY^SQU^SSC^T^Son_dead_cow^T^SST^T^S1^T^Sb^T^N1^T^Sn^S2^Scond^T^N1^T^N1^T^Si^Sunit_name^Sa^T^N1^Starget^t^t^N2^S==^N3^T^Sv^SCow^t^t^N2^S+^N3^T^N1^T^Si^Sunit_is_dead^t^N2^S==^N3^T^Si^Sunit_is_dead^Sa^T^N1^Starget^t^t^t^t^t^t^St^Sbranch^t^S3^T^Si^N1^Ss^N0^St^Sdelay^Sd^N5^Sc^N1^Sn^S4^t^S2^T^Se^T^N1^T^Sid^Stext^Sargs^T^N1^SYou~`hear~`a~`mysterious~`voice.~`"Dead~`cows~`will~`do~`you~`no~`good~`mortal!"^N2^N1^t^t^t^St^Slist^Sn^S3^t^S5^T^Se^T^N1^T^Sid^Squest_goToStep^Sargs^T^N1^S1117132053Mduyc~`to_find_or_not_to_find_~`step_2_^t^t^t^St^Slist^t^S4^T^Se^T^N1^T^Sid^Squest_markObjDone^Sargs^T^N1^S1117132053Mduyc~`to_find_or_not_to_find_^N2^Skill_cow^t^t^t^St^Slist^Sn^S5^t^t^t^t^SLI^T^t^SMD^T^SMO^SNO^t^SHA^T^t^SBA^T^SIC^SSpell_Nature_Polymorph_Cow^SDE^SLook~`for~`a~`cow~`and~`slay~`it~`to~`find~`the~`cow~`level.^SPR^B^SNA^SFInding~`it^SIN^b^t^SIN^T^t^SST^T^Sstep_1_first^T^SMD^T^SMO^SNO^t^SBA^T^SIN^B^SNA^Sstep_1_first^STX^SLooking~`for~`the~`cow~`level.^SFI^b^t^SSC^T^t^SHA^T^t^STY^SST^SLI^T^t^SIN^T^t^SAC^T^t^t^Sstep_2_^T^SMD^T^SMO^SNO^t^SBA^T^SIN^b^SNA^Sstep_2_^STX^Sfound~`no~`cow~`level.^SFI^B^t^SSC^T^t^SHA^T^t^STY^SST^SLI^T^t^SIN^T^t^SAC^T^t^t^t^SOB^T^Skill_cow^T^STX^SFind~`a~`cow~`and~`slay~`it.^SAA^B^t^t^t^t^SMD^T^SCD^S17/11/18~`13:20:53^SCB^SKazandra-WyrmrestAccord^SV^N26^SSB^SKazandra-WyrmrestAccord^SMO^SNO^SdV^S1.2.0^StV^N1013^SSD^S17/11/18~`14:04:28^SLO^Sen^t^SND^T^t^SHA^T^t^SsecurityLevel^N3^SBA^T^SIC^SSpell_Nature_Polymorph_Cow^SRA^S1~`-~`100^SDE^SYour~`mission~`is~`to~`find~`the~`cow~`level~`should~`you~`choose~`to~`accept~`it~`you~`will~`be~`rewarded~`handsomely.^SIM^SGarrZoneAbility-Stables^SNA^SThe~`Cow~`Level^t^SLI^T^t^SAC^T^t^t^N4^S1.2.0^t^^

**Comment by lindiwe-b** [comment]
Hi there, I finally got some time to sit and play around with this. It is still giving me an LUA error even after confirming. I think I am going to try to go through the "Cow Level" tutorial again fresh when I have some time as I think I might have missed some things. If I am still getting errors I will post again. I really would love to get this going for my guilds.
