### ISSUE TITLE
Close inventory/Sounds history on Esc button press

### ISSUE THREAD

**Issue by Solanya** [Ellypse/Total-RP-3-Extended#28]
Minor quality of life, it would be nice if pressing Esc would close those two windows as it does with most other windows in the addon.

*If I forget to make an issue ticket, the NPC Speech window suffers from the same omission.*

**Comment by Ellypse** [comment]
Don't forget to use `TRP3_API.ui.misc.playUISound(soundID)` instead of using directly `PlaySound()` so we follow the settings to have UI sound or not.
